### ISSUE TITLE
.tavis.yml build step doesn't work on jenkins v1.598

### ISSUE THREAD

**Issue by Dinoshauer** [masaki/jenkins-travis-yml-plugin#10]
Hi, trying to figure out how to use your plugin.

I'm getting the following message in my jenkins log when I save a build using the .travis.yml builder:

    getConfigPage -> /travis_yml_builder/config

This is all it logs, and when I go to reconfigure the build the build step is now gone, so it is removed on saves. Any ideas?

**Comment by velo** [comment]
I got the same problem here!

I'm using 1.598 as well.  Anything I can do to help this to be fixed?

**Comment by Nyholm** [comment]
Same here. 
Is this plugin abandoned? I would really need a plugin like this and I'm considering building my own if the owner does not give some love to this one

**Comment by kanekotic** [comment]
I am helping now sustain this plugin, I know this Issue is old but could you elaborate or can I close?

**Comment by kanekotic** [comment]
closing because its working in newer version of jenkins tested in  2.19.1
