### ISSUE TITLE
travis.yml $PATH not inheriting build $PATH

### ISSUE THREAD

**Issue by zeroecco** [masaki/jenkins-travis-yml-plugin#15]
Issue:
.travis.yml parser doesn't inherit job path.

env path is `/bin:/usr/bin:/sbin:/usr/sbin` on builds (got this from a build of mine). This path doesn't work with OSX because everything outside of core install is in `/usr/local/sbin` so node etc will not be useable unless you specify the full path.

**Comment by alvarolorentedev** [comment]
hello @zeroecco sorry i didn't get notified of your message.
We are forwarding enviroment variables in the latests versions of this plugin. I am not sure what your request is. But if you dont have access to certain specific routes you have a few options:
- Add extra paths to your `path` enviroment variable through your .profile.
- Add an enviroment variable that defines the specific path. Then you can use this in the `.travis.yml`. This can be done at node level, or project level.
- Call with the relative path based on the current build directory.

I am not sure if i have helped answer your question. In any case let me know. And again sorry i did not answer beofre but didnt get any notification.

**Comment by alvarolorentedev** [comment]
closing this as it has been 20 days without feedback, if you have any other question @zeroecco let me know, and i will try to help.
