### ISSUE TITLE
SSH_AUTH_SOCK from SSH Agent Plugin is not preserved

### ISSUE THREAD

**Issue by seschwar** [masaki/jenkins-travis-yml-plugin#7]
I want to use the [SSH Agent Plugin](https://wiki.jenkins-ci.org/display/JENKINS/SSH+Agent+Plugin) in order to allow a `composer install` build step to fetch my custom bundles from my private repositories.

The environment variable `SSH_AUTH_SOCK` then is present during usual Jenkins build steps.  This will make Git use the defined credentials. However during the individual actions like `install` and `script` defined in `.travis.yml` the environment variable is missing.

This prevents me from fully describing the build process in `.travis.yml`. Therefore i think the environment variable `SSH_AUTH_SOCK` should be whitelisted and be pass the individual Travis actions.

**Comment by kanekotic** [comment]
I am helping sustain this plugin, I know this Issue is old but could you elaborate or can I close?

**Comment by kanekotic** [comment]
this should be have solved in version 0.2.0 as there is no update from creator I will close
