### ISSUE TITLE
after_script is run before after_success

### ISSUE THREAD

**Issue by seschwar** [masaki/jenkins-travis-yml-plugin#8]
The documentation for the [Travis Build-Livecycle](http://docs.travis-ci.com/user/build-configuration/#Build-Lifecycle) mentions that `after_script` is executed after `after_success` and `after_failure`.

However this plugin executes `after_script` immediately after `script`, even before `after_success` and `after_failure`.

I think this plugin should execute them in the same way as Travis does.

**Comment by kanekotic** [comment]
solved in latest pull request
